[#555] Response-only Streaming
linkedin/rest.li pull request #556
Opened 2021-03-12 22:57 UTC by zizhong

Details can be found in https://github.com/linkedin/rest.li/issues/555.

2021-03-12 22:57 UTC, zizhong commented
cc @nizarm @ssheng

2021-03-15 23:49 UTC, nizarm requested changes
Looking really good. Can we also have integration tests written for these under R2-int-test module? Maybe for the below combinations with the RestRequestStreamResponse API

1. Rest Echo and Stream Response 
2. Timeout
3. Rest request Compression
4. Stream Response Compression

2021-03-15 23:49 UTC, nizarm commented on r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http/HttpNettyResponseOnlyStreamClient.java
> +import com.linkedin.r2.transport.http.client.stream.AbstractNettyStreamClient;
Unused import ``AbstractnettyStreamClient``

2021-03-15 23:49 UTC, nizarm commented on r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http/HttpNettyResponseOnlyStreamClient.java
> + * @author Zhenkai Zhu
Please update the author section since this is a new file

2021-03-15 23:49 UTC, nizarm commented on r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http/HttpNettyResponseOnlyStreamClient.java
> +   *
Create a new ResponseOnlyStreamClient?

2021-03-15 23:49 UTC, nizarm commented on r2-netty/src/main/java/com/linkedin/r2/transport/http/client/stream/http2/Http2NettyResponseOnlyStreamClient.java
> + */
Please update the @author section, since this is a new file

2021-03-27 02:01 UTC, zizhong commented
Put this work on hold as this requires either excessive refactor or additional flags. So that we decided to make the record-and-replay patch to resolve the issue quickly.
The record-and-replay part is https://github.com/linkedin/rest.li/pull/574

2021-03-27 02:01 UTC, closed without merging