[#573] BackupRequest doesn't work with streaming
linkedin/rest.li pull request #574
Opened 2021-03-27 01:47 UTC by zizhong

Details can be found in #573.
The fix is to buffer the body and resend if needed.

cc @nizarm @ssheng

2021-03-31 07:05 UTC, zizhong commented on d2/src/main/java/com/linkedin/d2/balancer/clients/BackupRequestsClient.java
> +    if (!isFullRequest(requestContext)) {
@nizarm Yes, we require them to set the flag if they want to use backup request with streaming.

2021-03-31 07:15 UTC, nizarm commented on d2/src/main/java/com/linkedin/d2/balancer/clients/BackupRequestsClient.java
> +    if (!isFullRequest(requestContext)) {
Sounds good

2021-03-31 07:29 UTC, nizarm reviewed
Can you check why the travis build is failing?

2021-03-31 22:26 UTC, zizhong commented
@nizarm I figured we need to use the same copy of RequestContext when sending request so that the targetHostHint can work.

2021-04-01 00:33 UTC, nizarm requested changes

2021-04-01 00:36 UTC, zizhong commented on d2/src/main/java/com/linkedin/d2/balancer/clients/BackupRequestsClient.java
> +          _client.doRequest(request, needCloneRC ? _requestContext.clone(): _requestContext, new Callback<T>()
@nizarm Sorry, but I think you are reviewing an outdated diff. Please check the latest. Thanks!

2021-04-01 00:40 UTC, nizarm approved these changes

2021-04-01 00:41 UTC, nizarm commented
Nice work, thanks for taking care of this usecase

2021-04-01 01:52 UTC, merged