Modified the service-cluster mapping for regular service Znodes to be…
linkedin/rest.li pull request #750
Opened 2022-01-20 20:33 UTC by JieyingXu

Modified the service-cluster mapping for regular service Znodes to be consistent with the change in d2-config-service.

Before the change, regular service Znode will be mapped to clusterA-localColo, e.g. clusterA-WestCoast.
After the change, it will be mapped to clusterA. The local colo suffix will not present.
This is to remove the requirements on operation orders when enabling/disabling cross colo routing to prevent errors.

2022-01-21 06:51 UTC, rickzx requested changes
Please make sure to update gradle.properties and run ./script/update_changelog

2022-01-22 20:21 UTC, bohhyang reviewed
echo Rick's comment.

2022-01-25 00:28 UTC, rickzx requested changes

2022-01-25 00:28 UTC, rickzx commented on CHANGELOG.md
> +- Modified the service-cluster mapping for regular service Znodes to be consistent with the change in d2-config-service.
Let's not mention d2-config-service as this is a LI-internal MP.
I would prefer `Map local variant of service ZNodes to cluster without colo suffix`

2022-01-25 00:53 UTC, rickzx approved these changes

2022-01-25 02:00 UTC, bohhyang approved these changes
lgtm. thx

2022-01-25 20:06 UTC, merged